### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by lquessenberry** [xtjoeywx/docker-mautic-nginx-letsencrypt#1]
I have waited for several minutes and I still get a 503 service temporarily unavailable. What can I send to you to look at to see where I am messing up?

**Comment by xtjoeywx** [comment]
Hi. Sorry for my delay. I didn't get notified for some reason. Are you still having an issue or did it fix? A lot of solutions to problems people were having regarding the ssl certificate, which is what it sounds like you are having, have been addressed here: https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/issues?q=is%3Aissue+is%3Aclosed
However, if you can't find your solution there, please come back here to give me more details on what you are experiencing.

**Comment by lquessenberry** [comment]
Sorry for the delay on my end. I have a new issue but I will post it as a new one.
